wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.29
    framework: huggingface
    huggingface_version: 4.5.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.29
      6: 4.5.0
      8:
      - 5
